<!DOCTYPE html>
<html lang="en">
<head>
    <?= var_dump($_SESSION); ?>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Rubik">
    <link rel="stylesheet"href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
    <script src="js/script.js"></script>
    <title><?php echo $view?></title>
    <nav>
        <?php include("tpl/".isLogged().".phtml"); ?>
    </nav>
</head>
<body>
    <?php include("view/".$view.".phtml"); ?>
</body>
</html>