<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"href="https://fonts.googleapis.com/css?family=Rubik">
    <link rel="stylesheet"href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
    <script src="js/script.js"></script>
    <title><?php echo $view?></title>
</head>
<body>
    <header>
    <?= var_dump($_SESSION); ?>
        <nav>
            <li>
                <?php include("tpl/".$nav.".phtml"); ?>
            </li>
        </nav>
    </header>
    <main>
        <?php include("view/".$view.".phtml"); ?>
    </main>
    <footer>

    </footer>
</body>
</html>