<section class="addContent">
<p id="error"><?php if ($error != ""): echo $error; endif ?></p>
    <form action="addArticle.php" method="POST">
        <p>Entrez un titre d'article: </p>
        <p><input type="text" name="titre" value="<?= $titre ?>" required></p>
        <p>Entrez votre article:</p> 
        <p><textarea name="article" id="" cols="30" rows="10"><?= $article ?></textarea></p>
        <p> Veuillez choisir une catégorie: </p>  
        <p><select name="category" id="category" required>
        <?php foreach ($categories as $a): ?>
            <option value="<?= $a['id'] ?>"><?= $a['nom']  ?></option>
        <?php endforeach ?>
        </select></p>
        <p><button type="submit" class="send">Confirmez</button></p>
    </form>
</section>
