<section class="addContent">
    <form action="addArticle.php" method="POST">
        <p>Entrez votre article:</p> 
        <p><textarea name="article" id="" cols="30" rows="10"><?= $article ?></textarea></p>
        <p> Veuillez choisir une catégorie: </p>  
        <p><select name="category" id="category">
        <?php foreach ($categories as $a): ?>
            <option value="<?= $a['id'] ?>"><?= $a['nom']  ?></option>
        <?php endforeach ?>
        </select></p>
        <p><button type="submit">Confirmez</button></p>
    </form>
</section>
