<?php if(array_key_exists('id', $_GET)): ?>
    <section class="container">
        <p id="error"></p>
        <article class="article">
            <input type="hidden" id="idArticle" value="<?= $data['id'] ?>">
            <h2><?= $data['titre'] ?></h2>
            <article>
                <p>
                    <?= nl2br($data['article'])  ?>
                </p>
            </article>
            <h3><a href="article.php?category=<?= getContent('categories', $data['id_categorie'])['id'] ?>"><?= getContent('categories', $data['id_categorie'])['nom'] ?></a></h3>
            <p>Publiée le <?= $data['date'] ?> par <?= getContent('utilisateurs', $idUtilisateur)['username'] ?> </p>
        </article>
        <section id="commentsList">
            <?php if (isLogged() == "navAdmin" || isLogged() == "navUser"): ?>
                <input type="hidden" id="idUser" value="<?= $_SESSION['user']['id'] ?>">
                <section class="sendComment">
                    <textarea name="comment" id="comment" cols="20" rows="10"></textarea>
                    <button type="submit" id="post" class="send">Envoyez</button>
                </section>
            <?php endif ?>
        <?php foreach ($comments as $c): ?>
            <section class="comment" id="<?= $c['id'] ?>">
                <p><?= getContent('utilisateurs', $c['id_utilisateur'])['username'] ?></p>
                <p><?= $c['commentaires'] ?></p>
                <p><?= $c['date'] ?></p>
                <?php if (isLogged() == "navAdmin" || $_SESSION['user']['id'] == $c['id_utilisateur']): ?>
                    <form action="delComment.php" method="post">
                        <input type="hidden" name="idArticle" value="<?= $data['id'] ?>">
                        <button type="submit" name="id" value="<?= $c['id'] ?>" class="del">Supprimer</button>
                    </form>
                <?php endif ?>
            </section>
        <?php endforeach ?>
        </article>
    </section>
<?php else: ?>
    <section class="articleList container">
        <?php foreach ($data as $a): ?>
            <article class="article">
            <a href="article.php?id=<?= $a['id']?>">
                <h2><?= $a['titre'] ?></h2>
                <h3><a href="article.php?category=<?= getContent('categories', $a['id_categorie'])['id'] ?>"><?= getContent('categories', $a['id_categorie'])['nom'] ?></a></h3>
                <p> <?= limit_text($a['article'], 20) ?></p>
                <h6>Publiée le: <?= $a['date'] ?> par <?= getContent('utilisateurs', $a['id_utilisateur'])['username'] ?> </h6>
            </a>
            </article>
        <?php endforeach ?>
    </section>
<?php endif ?>
