<form action="createAccount.php" method="POST">
    <p>Entrez un nom d'utilisateur: <input type="text" name="username" value="<?= $username ?>" required></p>
    <p>Entrez votre e-mail: <input type="email" name="email" id="" value="<?= $email ?>" required></p>
    <p>Entrez un mot de passe: <input type="password" name="password" id="" required></p>
    <p>Confirmer votre mot de passe: <input type="password" name="passwordConfirm" id="" required></p>
    <button type="submit">Confirmez</button>
</form>