<form action="createAccount.php" method="POST">
    <p>Entrez un nom d'utilisateur: <input type="text" name="username"></p>
    <p>Entrez votre e-mail: <input type="email" name="email" id=""></p>
    <p>Entrez un mot de passe: <input type="password" name="password" id=""></p>
    <p>Confirmer votre mot de passe: <input type="password" name="passwordConfirm" id=""></p>
    <button type="submit">Confirmez</button>
</form>