<a href="addArticle.php">Ajouter un article</a>
<table class="listContent">
    <thead>
        <tr>
            <th>Id</th>
            <th>Article</th>
            <th>Auteur</th>
            <th>Catégorie</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($data != false): ?>
            <?php foreach ($data as $i): ?>
                <tr class="listContent">
                <th><?= $i['id'] ?></th>
                <th><?= $i['article'] ?></th>
                <th><?= getContent('utilisateurs', $i['id_utilisateur'])['username']  ?></th>
                <th><?= getContent('categories', $i['id_categorie'])['nom']  ?></th>
                <th><?= $i['date'] ?></th>
                <th>
                    <form action="editArticle.php" method="post">
                        <button type="submit" name="id" value="<?= $i['id'] ?>">Modifier</button>
                    </form>
                </th>
                <th>
                    <form action="delArticle.php" method="post">
                        <button type="submit" name="id" value="<?= $i['id'] ?>">Suprimmer</button>
                    </form>
                </th>
                </tr>
            <?php endforeach ?>
        <?php else: ?>
            <p>Aucun article n'est disponible.</p>
        <?php endif ?>
    </tbody>
</table>
