<a href="addCategory.php">Ajouter une catégorie</a>
<table class="listContent">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nom de catégorie</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($data != false): ?>
            <?php foreach ($data as $i): ?>
                <tr class="listContent">
                <th><?= $i['id'] ?></th>
                <th><?= $i['nom'] ?></th>
                <th>
                    <form action="editCategory.php" method="post">
                        <button type="submit" name="id" value="<?= $i['id'] ?>">Modifier</button>
                    </form>
                </th>
                <th>
                    <form action="delCategory.php" method="post">
                        <button type="submit" name="id" value="<?= $i['id'] ?>">Suprimmer</button>
                    </form>
                </th>
                </tr>
            <?php endforeach ?>
        <?php else: ?>
            <p>Aucune catégorie n'est disponible.</p>
        <?php endif ?>
    </tbody>
</table>
