<a href="addCategory.php">Ajouter une catégorie</a>

<?php if ($data != false): ?>
    <?php foreach ($data as $i): ?>
        <p>Id: <?= $i['id'] ?></p>
        <p>Name: <?= $i['nom'] ?></p>
        <form action="editCategory.php" method="post">
            <button type="submit" name="id" value="<?= $i['id'] ?>">Modifier</button>
        </form>
        <form action="delCategory.php" method="post">
            <button type="submit" name="id" value="<?= $i['id'] ?>">Suprimmer</button>
        </form>
    <?php endforeach ?>
<?php else: ?>
    <p>Aucune catégorie n'est disponible.</p>
<?php endif ?>