<h1 class="add"><a href="addCategory.php">Ajouter une catégorie</a></h1>
<p id="error"><?php if ($error != ""): echo $error; endif ?></p>
<table class="listContent" cellspacing="0" cellpadding="0">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nom de catégorie</th>
            <th colspan="2">Edition</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($data != false): ?>
            <?php foreach ($data as $i): ?>
                <tr class="listContent">
                <td><?= $i['id'] ?></td>
                <td><?= $i['nom'] ?></td>
                <td>
                    <form action="editCategory.php" method="post">
                        <button type="submit" name="id" value="<?= $i['id'] ?>">Modifier</button>
                    </form>
                </td>
                <td>
                    <form action="delCategory.php" method="post" onsubmit="return window.confirm('Vous êtes sur de vouloir supprimer cette catégorie?');">
                        <button type="submit" name="id" value="<?= $i['id'] ?>">Supprimer</button>
                    </form>
                </td>
                </tr>
            <?php endforeach ?>
        <?php else: ?>
            <h2 id="error">Aucune catégorie n'est disponible.</h2>
        <?php endif ?>
    </tbody>
</table>
