<section class="addContent">
<p class="error"><?php if ($error != ""): echo $error; endif ?></p>
    <form action="profil.php" method="POST">
        <p>Nom d'utilisateur:</p>
        <p><input type="text" name="username" value="<?= $user['username'] ?>"></p>
        <p>E-mail</p>
        <p><input type="email" name="email" value="<?= $user['email'] ?>"></p>
        <p>Modifier votre mot de passe:</p>
        <p><input type="password" name="password" id=""></p>
        <p>Confirmer votre nouveau mot de passe: </p>
        <p><input type="password" name="passwordConfirm" id=""></p>
        <p><button type="submit">Modifier</button></p>
    </form>
    <!-- <form action="delUser.php" method="post" onsubmit="return window.confirm('Vous êtes sur de vouloir supprimer ce compte?');">
        <p><button type="submit" name="id" value="<?= $_SESSION['user']['id']?>">Supprimer</button></p>
    </form> -->
</section>